generic-service:
  nameOverride: hmpps-visits-prison-config-service
  serviceAccountName: visit-someone-in-prison
  productId: "DPS035"
  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-visits-prison-config-service
    tag: app_version
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-visits-prison-config-service-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-visits-prison-config-service:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-visits-prison-config-service
