version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@10

parameters:
  alerts-slack-channel:
    type: string
    default: visits-alerts
  releases-slack-channel:
    type: string
    default: visits-alerts

jobs:
  validate:
    executor:
      name: hmpps/java_postgres
      jdk_tag: "21.0"
      postgres_tag: "15"
      postgres_username: "visit_scheduler"
      postgres_password: "visit_scheduler"
      postgres_db: "visit_scheduler"
    environment:
      _JAVA_OPTIONS: -Xmx500m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - hmpps/wait_till_ready_postgres
      - run:
          name: Install git and flyway
          command: |
            sudo apt-get update && sudo apt-get install -y git
            curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.10/flyway-commandline-8.5.10-linux-x64.tar.gz -o flyway.tar.gz
            tar -xzf flyway.tar.gz
            sudo ln -s `pwd`/flyway-8.5.10/flyway /usr/local/bin/flyway
      - run:
          name: Get flyway migrations from visit-scheduler
          command: |
            git clone https://github.com/ministryofjustice/visit-scheduler.git
            cp -r visit-scheduler/src/main/resources/db/migration ./migrations
      - run:
          name: Run migrations
          command: |
            flyway -url=jdbc:postgresql://localhost:5432/visit_scheduler -user=visit_scheduler -password=visit_scheduler -locations=filesystem:./migrations migrate
      - run:
          name: Run checkstyle and integration tests
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-deploy-main:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - main

      - hmpps/helm_lint:
          name: helm_lint
          filters:
            branches:
              only:
                - main

      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main

      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint

      - hmpps/deploy_env:
          name: deploy_staging
          env: "staging"
          context:
            - hmpps-common-vars
            - visit-someone-in-prison-backend-svc-staging
          filters:
            branches:
              only:
                - main
          requires:
            - deploy_dev

      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - visit-someone-in-prison-backend-svc-preprod
          filters:
            branches:
              only:
                - main
          requires:
            - request-preprod-approval
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only:
                - main

      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - visit-someone-in-prison-backend-svc-prod
          filters:
            branches:
              only:
                - main
          requires:
            - request-prod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
          filters:
            branches:
              only:
                - main

  build-test-deploy-feature:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main

      - hmpps/helm_lint:
          name: helm_lint
          filters:
            branches:
              ignore:
                - main

      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              ignore:
                - main

      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              ignore:
                - main
          requires:
            - request-dev-approval
      - request-dev-approval:
          type: approval
          requires:
            - validate
            - build_docker
            - helm_lint
          filters:
            branches:
              ignore:
                - main

      - hmpps/deploy_env:
          name: deploy_staging
          env: "staging"
          context:
            - hmpps-common-vars
            - visit-someone-in-prison-backend-svc-staging
          filters:
            branches:
              ignore:
                - main
          requires:
            - request-staging-approval
      - request-staging-approval:
          type: approval
          requires:
            - validate
            - build_docker
            - helm_lint
          filters:
            branches:
              ignore:
                - main

  security:
    triggers:
      - schedule:
          cron: "7 6 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          cache_key: "v2_0"
          jdk_tag: "21.0"
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          jdk_tag: "21.0"
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "12 6 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          jdk_tag: "21.0"
          context:
            - veracode-credentials
            - hmpps-common-vars


