---
# Per environment values which override defaults in hmpps-visits-prison-config-service/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-visits-prison-config-service-preprod.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"

generic-prometheus-alerts:
  alertSeverity: visits-alerts-nonprod
